import '../explore_page/widgets/categories1_item_widget.dart';import '../explore_page/widgets/categories_item_widget.dart';import 'models/categories1_item_model.dart';import 'models/categories_item_model.dart';import 'notifier/explore_notifier.dart';import 'package:flutter/material.dart';import 'package:test1/core/app_export.dart';import 'package:test1/widgets/app_bar/appbar_title_searchview.dart';import 'package:test1/widgets/app_bar/appbar_trailing_image.dart';import 'package:test1/widgets/app_bar/custom_app_bar.dart';class ExplorePage extends ConsumerStatefulWidget {const ExplorePage({Key? key}) : super(key: key);

@override ExplorePageState createState() =>  ExplorePageState();

 }
class ExplorePageState extends ConsumerState<ExplorePage> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 25.v), child: Column(children: [_buildManFashion(context), SizedBox(height: 37.v), _buildWomanFashion(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(title: Consumer(builder: (context, ref, _) {return AppbarTitleSearchview(margin: EdgeInsets.only(left: 16.h), hintText: "lbl_search_product".tr, controller: ref.watch(exploreNotifier).searchController);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLoveIcon, margin: EdgeInsets.only(left: 16.h, top: 16.v, right: 16.h)), Container(height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 16.h, top: 16.v, right: 32.h), child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgNotificationIcon, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center, onTap: () {onTapImgNotificationIcon(context);}), CustomImageView(imagePath: ImageConstant.imgClosePink300, height: 8.adaptSize, width: 8.adaptSize, alignment: Alignment.topRight, margin: EdgeInsets.only(left: 14.h, right: 2.h, bottom: 16.v))]))]); } 
/// Section Widget
Widget _buildManFashion(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_man_fashion".tr, style: theme.textTheme.titleSmall), SizedBox(height: 13.v), Consumer(builder: (context, ref, _) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 94.v, crossAxisCount: 4, mainAxisSpacing: 21.h, crossAxisSpacing: 21.h), physics: NeverScrollableScrollPhysics(), itemCount: ref.watch(exploreNotifier).exploreModelObj?.categoriesItemList.length ?? 0, itemBuilder: (context, index) {CategoriesItemModel model = ref.watch(exploreNotifier).exploreModelObj?.categoriesItemList[index] ?? CategoriesItemModel(); return CategoriesItemWidget(model);});})]); } 
/// Section Widget
Widget _buildWomanFashion(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_woman_fashion".tr, style: theme.textTheme.titleSmall), SizedBox(height: 13.v), Consumer(builder: (context, ref, _) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 93.v, crossAxisCount: 4, mainAxisSpacing: 21.h, crossAxisSpacing: 21.h), physics: NeverScrollableScrollPhysics(), itemCount: ref.watch(exploreNotifier).exploreModelObj?.categories1ItemList.length ?? 0, itemBuilder: (context, index) {Categories1ItemModel model = ref.watch(exploreNotifier).exploreModelObj?.categories1ItemList[index] ?? Categories1ItemModel(); return Categories1ItemWidget(model);});})]); } 
/// Navigates to the notificationScreen when the action is triggered.
onTapImgNotificationIcon(BuildContext context) { NavigatorService.pushNamed(AppRoutes.notificationScreen, ); } 
 }
